import { Fragment } from 'react'
import Head from 'next/head'
import blogItem from '../components/BlogItem/blogItem';

const BLOG_POST = [
  {id: 1, title: "first blog", image:"https://images.unsplash.com/photo-1676287258876-388ff4f4b48b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80", description: "este es mi primer blog", details: "sigo haciendo pruebas"},
  {id: 2, title: "second blog", image:"https://plus.unsplash.com/premium_photo-1673716791365-6f15a6e2c7ad?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80", description: "este es mi segundo blog", details: "probando tw next y mongo"}
]

console.log(BLOG_POST);


function Home() {
  return (
    <>
    <Fragment>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,400;0,500;0,600;1,300&family=Outfit:wght@700;900&family=Raleway:wght@100;200&display=swap" rel="stylesheet" />
      </Head>
      <div class="container items-center justify-items-center">
        <h1 className="text-[50px] font-bold text-center">Blog Page</h1>
        {BLOG_POST.map((blog) => (
          <div key={blog.id} className="flex flex-col">
            <blogItem 
            title={blog.title} 
            mage={blog.image} 
            description={blog.description} 
            details={blog.details}
            />
          </div> 
        ))}
      </div>
      </Fragment>
    </>
  )
}


export default Home;